version: "3.0"
services:
  revenue-collection:
    image: yousebe:latest
    container_name: yousebe
    ports:
      - "8082:8081"
    depends_on:
      - mysql-db
#      - rabbitmq

  mysql-db:
    image: mysql:5.7
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'yousebe'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
#  rabbitmq:
#    image: rabbitmq:management
#    restart: always
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
volumes:
  yousebe-files:
    external: true
  mysql-db:
